### ISSUE TITLE
double entry enumeration schema

### ISSUE THREAD

**Issue by rsoeldner** [PistoiaAlliance/UDM#1]
Just encountered many duplicate entries in the result_types schema. Any reason for this ?

See this example:
https://github.com/PistoiaAlliance/UDM/blob/47ad0e53d8c7b68dc1de32d97311df7cafa44e63/udm_6_0_0_result_types.xsd#L76-L77

**Comment by JarekT5k** [comment]
Apologies for the late response.  I've fixed the file.  The reason was that initially, we had looked at abbreviated names and I didn't clean them up afterwards.  Thank you for letting us know!
